// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbdffuojryzhwbtlyczj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiZGZmdW9qcnl6aHdidGx5Y3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzMwNTIsImV4cCI6MjA2NDY0OTA1Mn0.6sH9TKHepur8tl5L8tbEcbRot3lE7CMpXn6oNMUhMT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);